from pathlib import Path

ADDONS_TEXT = Path("resources/addons.txt").read_text()
ABOUT_TEXT = Path("resources/about.txt").read_text()
RULES_TEXT = Path("resources/rules.txt").read_text()
RANKS_TEXT = Path("resources/ranks.txt").read_text()
TIMES_TEXT = Path("resources/times.txt").read_text()
APPLICATION_TEXT = Path("resources/application.txt").read_text()
APPLICATION_PUBLIC_TEXT = Path("resources/application_public.txt").read_text()
APPLICATION_SUBMITTED_TEXT = Path("resources/application_submitted.txt").read_text()
APPLICATION_SUBMIT_MISSING_ARMORY = Path("resources/application_submit_missing_armory.txt").read_text()
APPLICATION_SUBMIT_MISSING_LOGS = Path("resources/application_submit_missing_logs.txt").read_text()
APPLICATION_SUBMIT_MISSING_WHY = Path("resources/application_submit_missing_why.txt").read_text()
APPLICATION_SUBMIT_MISSING_XP = Path("resources/application_submit_missing_xp.txt").read_text()
APPLICATION_SUBMIT_MISSING_RAIDERIO = Path("resources/application_submit_missing_raiderio.txt").read_text()
APPLICATION_SUBMIT_ALREADY = Path("resources/application_submit_already.txt").read_text()
APPLICATION_ACCEPTED_TEXT = Path("resources/application_accepted.txt").read_text()
APPLICATION_ACCEPTED_RESPONSE_TEXT = Path("resources/application_accepted_response.txt").read_text()
APPLICATION_REJECTED_TEXT = Path("resources/application_rejected.txt").read_text()
APPLICATION_REJECTED_RESPONSE_TEXT = Path("resources/application_rejected_response.txt").read_text()
APPLICATION_REJECTED_NOT_APPLICANT_TEXT = Path("resources/application_rejected_not_applicant.txt").read_text()
APPLICATION_DEFAULT_REJECTION_REASON_TEXT = Path("resources/application_default_rejection_reason.txt").read_text()
APPLICATION_PROVIDED_XP_TEXT = Path("resources/application_provided_xp.txt").read_text()
APPLICATION_PROVIDED_WHY_TEXT = Path("resources/application_provided_why.txt").read_text()
APPLICATION_PROVIDED_LOGS_TEXT = Path("resources/application_provided_logs.txt").read_text()
APPLICATION_PROVIDED_ARMORY_TEXT = Path("resources/application_provided_armory.txt").read_text()
APPLICATION_PROVIDED_RAIDERIO_TEXT = Path("resources/application_provided_raiderio.txt").read_text()
ALTS_TEXT = Path("resources/alts.txt").read_text()
PREPARATION_1_TEXT = Path("resources/preparation.1.txt").read_text()
PREPARATION_2_TEXT = Path("resources/preparation.2.txt").read_text()
ON_MEMBER_JOIN_1_TEXT = Path("resources/on_member_join.1.txt").read_text()
ON_MEMBER_JOIN_2_TEXT = Path("resources/on_member_join.2.txt").read_text()

FRIEND_ROLE_ASSIGNED_TEXT = Path("resources/friend_role_assigned.txt").read_text()
FRIEND_ROLE_ALREAD_ASSIGNED_TEXT = Path("resources/friend_role_already_assigned.txt").read_text()
